fixed the grid issue
AbhiPatel10/openzone pull request #58
Opened 2024-05-15 03:40 UTC by Ankitapanda25

## Fixes #20 

## Changes proposed
the grid is made responsive according to the screen sizes
the text doesnt overflow anymore
the links of the URLs were made clickable
the links open in a separate tab

## Screenshots
[screen-capture (1).webm](https://github.com/AbhiPatel10/openzone/assets/123666302/1cd61a1e-6766-4bd4-8302-8604ab6fd26e)

## Note to reviewers
Please review my PR under GSSOC'24 and do give a feedback

2024-05-15 03:41 UTC, Ankitapanda25 commented
@AbhiPatel10 Please review my PR, it closes issue #20

2024-05-16 17:36 UTC, AbhiPatel10 requested changes

2024-05-16 17:36 UTC, AbhiPatel10 commented on src/styles/global.css
> +html{
Do not use overflow like this, If You facing overflow issue then find the reason of overflow and solve it there.

2024-05-16 17:36 UTC, AbhiPatel10 commented on package-lock.json
Please Remove This File

2024-05-18 15:52 UTC, AbhiPatel10 commented on .gitignore
> +/package-lock.json
Thanks For adding this

2024-05-18 15:52 UTC, AbhiPatel10 approved these changes

2024-05-18 15:52 UTC, merged