menu Icon added!
AbhiPatel10/openzone pull request #63
Opened 2024-05-15 13:37 UTC by bro-maanii

Closes #41  

## Fixes Issue (before)
![image](https://github.com/AbhiPatel10/openzone/assets/125199246/5f3c1264-8a67-4722-8be2-22ce11f83a86)

## After
![image](https://github.com/AbhiPatel10/openzone/assets/125199246/ce6afa10-65fd-4387-9aec-913b1e11323d)

2024-05-16 17:38 UTC, AbhiPatel10 requested changes

2024-05-16 17:38 UTC, AbhiPatel10 commented on package-lock.json
Looks Good to me Just Remove this File

2024-05-18 07:25 UTC, bro-maanii commented on package-lock.json
done sir

2024-05-18 15:52 UTC, AbhiPatel10 approved these changes

2024-05-18 15:53 UTC, merged